create table if not exists public.workflow_sessions (
  telegram_chat_id bigint primary key,
  session_started_at timestamptz,
  session_deadline timestamptz,
  consecutive_no_count integer not null default 0,
  next_scan_at timestamptz,
  current_prompt_token uuid,
  current_prompt_url text,
  current_prompt_sent_at timestamptz,
  current_prompt_expires_at timestamptz,
  last_decision text check (last_decision in ('yes', 'no', 'missed', 'expired')),
  last_decision_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.workflow_prompt_events (
  id bigint generated by default as identity primary key,
  telegram_chat_id bigint not null,
  prompt_token uuid not null unique,
  url text not null,
  sent_at timestamptz not null,
  expires_at timestamptz not null,
  decision text check (decision in ('yes', 'no', 'missed', 'expired')),
  clicked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists workflow_prompt_events_chat_idx
  on public.workflow_prompt_events (telegram_chat_id, sent_at desc);

alter table public.workflow_sessions enable row level security;
alter table public.workflow_prompt_events enable row level security;

do $$
begin
  create policy "service role can manage workflow sessions"
  on public.workflow_sessions for all to service_role using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "service role can manage workflow prompt events"
  on public.workflow_prompt_events for all to service_role using (true) with check (true);
exception when duplicate_object then null;
end $$;